/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import práctica.pkg2.Práctica2;

/**
 *
 * @author Guada
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        this.setSize(500, 400);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        betaB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        moduloN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alfaA = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de cifrado");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 30, 230, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("Ingrese el valor de beta (b):");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 230, 230, 17);

        betaB.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        betaB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        betaB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        betaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaBActionPerformed(evt);
            }
        });
        jPanel1.add(betaB);
        betaB.setBounds(280, 220, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("Ingrese el valor del modulo (n):");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 230, 17);

        moduloN.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        moduloN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        moduloN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloNActionPerformed(evt);
            }
        });
        jPanel1.add(moduloN);
        moduloN.setBounds(280, 100, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("Ingrese el valor de alfa (a):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 230, 17);

        alfaA.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        alfaA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alfaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfaAActionPerformed(evt);
            }
        });
        jPanel1.add(alfaA);
        alfaA.setBounds(280, 160, 160, 30);

        jButton1.setBackground(new java.awt.Color(204, 102, 255));
        jButton1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 290, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, -1, 530, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void betaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betaBActionPerformed

    private void moduloNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduloNActionPerformed

    private void alfaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alfaAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        int n = Integer.parseInt(moduloN.getText());
        int a = Integer.parseInt(alfaA.getText());
        int b = Integer.parseInt(betaB.getText());

        String textoResultado = Práctica2.procesarCifrado(n, a, b);

        resultados ventanaRes = new resultados();
        
        ventanaRes.mostrarResultados(textoResultado);
        
        ventanaRes.setVisible(true);
        ventanaRes.setLocationRelativeTo(null); 
       

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, ingresa solo números enteros válidos.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            e.getMessage(), 
            "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alfaA;
    private javax.swing.JTextField betaB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField moduloN;
    // End of variables declaration//GEN-END:variables
}
